# Generated by Django 2.1.5 on 2019-01-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip_addr', models.CharField(max_length=200, verbose_name='ip address of cam')),
            ],
        ),
        migrations.AddField(
            model_name='frame',
            name='cam_id',
            field=models.IntegerField(default=0),
        ),
    ]
