# Generated by Django 2.1.5 on 2019-01-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0002_auto_20190120_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='position',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='frame',
            name='probability',
            field=models.FloatField(default=0),
        ),
    ]
